### ISSUE TITLE
'Classic Compute' should be 'ClassicCompute' in Get-ASCDataCollection

### ISSUE THREAD

**Issue by glaisne** [Microsoft/Azure-Security-Center#1]
the url path should be ClassicCompute rather than 'Classic Compute' (with the space) when trying to get security information for 'classic' VMs.

**Comment by glaisne** [comment]
tried to do a pull request and the CLA, but had issues. Fix is to make line 1028 this:
[ValidateSet('Compute','ClassicCompute')]

**Comment by Javanite** [comment]
Hi Glaisne,

Thank you for providing this feedback, unfortunately, the endpoint used by this cmdlet is being decommissioned by engineering so I had to remove the cmdlet altogether. I REALLY appreciate you providing the problem and the fix, however! It's very valuable. 

Closing this issue because Get-ASCDataCollection is now a deprecated cmdlet and has been removed in version 0.0.19.
